# Generated by Django 5.0.1 on 2024-01-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='movie_name')),
                ('writer', models.CharField(max_length=200, verbose_name='movie_writer_name')),
                ('released', models.BooleanField(default=True, verbose_name='is_movie_released')),
                ('producer', models.CharField(blank=True, null=True, verbose_name='movie_producer_name')),
                ('director', models.CharField(blank=True, null=True, verbose_name='movie_director_name')),
            ],
        ),
    ]
